name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Py ${{ matrix.python }} / Django ${{ matrix.django }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8, 3.9, 3.10, 3.11]
        django: [3.2, 4.2]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow
          pip install --upgrade Django==${{ matrix.django }}
          pip install --upgrade coveralls
      - name: Run Tests
        run: |
          python setup.py -q build
          export PYTHONWARNINGS="default"
          coverage run --source=. runtests.py
      - name: Submit to coveralls
        env:
          COVERALLS_FLAG_NAME: run-${{ matrix.python }}-${{ matrix.django }}
          COVERALLS_PARALLEL: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
  coveralls:
    name: Finish Coveralls
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Finished
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade coveralls
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
